export const messages = ["Whya galt bf makanch",
	"Golhoma. Ya3toni ",
	"Wah nichai ",
	"Karjah ",
	"Wah ",
	"Imail wismi ",
	"Minoichachaimaa@gmai.com ",
	"Cc 3andak ratrapag ta3 l3am li fat ta3 securite ",
	"Wtala3tah w walo ",
	"Saytha fasitah ",
	"Wl s3 nos swalah ma mafichynhomli ",
	"Psq halit progras s4 mamafichini walo ",
	"Esq kayan wahdin maaficholhom walo fi progras ",
	"Sayt progras matla3lich ",
	"Cc ",
	"?? ",
	"Kayan gir hada limail wkan 3labalkom ntoma ",
	"Charaslatli ",
	"Mata9rach tp 3andah ",
	"Salc tp esq ndiroh fi matlab ",
	"Bgit nsa9sik ",
	"Kont mrda 3liha mabantch ",
	"Salam ",
	"Hsabtak rdtah tilifoun ",
	"Yak ",
	"Yatla3 pc ",
	"Cc  cvp rsali hadak ta3 archtactur ",
	"Merci bzaf  ",
	"Chakrajana na9adro ",
	"Chkon li fihom li y9alal is abat ",
	"Cvp ida hdart hsa talya ta3 hadak sucurete elctriq nhar lhad lifat hambouk Rsali ",
	"Cc  ",
	"aya saha hambouk rani matfarja wahd 5vd w walo ",
	"aaaaa lakanch 3labali ",
	"merci ",
	"aaaaaa saha waha ",
	"yab9a hadak ta3raf trodah nta driv ",
	"aya say mala kayan kolch mliha ",
	"aaaa hadak bou asdya ",
	"ba9i ta3 musur whadak ta3 hadak elt ",
	"aya say la tla3 ma3lich ",
	"psq lprof gali raslihomli ",
	"yatla3 ",
	"kimahaka flgrop naraslah alas ",
	"rsali ta3 architactur ",
	" ",
	"cc ",
	"gadwa rah njibah tani ",
	"aaaa ma3lich ",
	"fl bibliotaq ",
	"aaa ma3lich ana min gotli rah na9ra mn g3at n9ara3 ",
	"saha ma3lich ",
	"aaaa wan ni hna n9ara3 ",
	"ana ni fl bibliotak ida ki tkamal ta9dar tji ",
	"cc ",
	"rahom fdraiv ",
	"say ma3lich merci ",
	"raslahli ",
	"svp ",
	"hambouk kasni ex tali ta3 fich 2 ",
	"cc  ",
	"bizar ",
	"yadra bdit enarg ",
	" ",
	"wah ",
	"hhhhhhhh adi wlah flkadma hado swalah machi  mansha9ohomch bzaf ",
	"hhhhhhhh ha chaft ana oma gir eln ",
	"say 9rit kolch apar eln ",
	"m9ithach ",
	"ana  lagalb eln mlbdya ta3 l3am ",
	"wah nichan nta tahsilha ",
	"3liha mabgitch ndaya3 wa9t fiha ndkol gir bfich 5 wsay ",
	"eln ni gat3a mnha lyas ",
	"b9ali ps eln fich 5 ",
	"kmltha ",
	"elt ",
	"ana dart ",
	"aya saha ",
	"ta3 energ ",
	"ta9dar tfahmni ex 1 ",
	"cc  ",
	"m ",
	"merci  ",
	"3la rabi nchakah yarabi ",
	"wah ana lafich ni fahmthom tb9a nahfad 9awanin ",
	"tkmama ",
	"mochkla tamarin ",
	"3la rabi ",
	"wlah ",
	"yajadk bzaf ",
	"tma kolch ",
	"ps  esq ga3 ",
	"wah ",
	"mohim n9ro ",
	"ma3lich ",
	"aya say ",
	"hada ni hasa ",
	"sohib ",
	"aya say mala ",
	"hado ta3 sohib ",
	"aya matansanich hambouk ",
	"aya saha min gotli gbilat 3andi golt 3andk ",
	"ta3 energ ",
	" hambouk rsali hadak lrusum li gotli 3lih ",
	"cc ",
	"aaaaaa saya fhamtak ",
	"makanch flyoutoub chaft makanch ",
	"saha w elt fich 5 ex 2   3 ",
	"adi  ana jit n9ra  ma9dartch ",
	" esq rak fahm ex 4 fich 3 ta3 math ",
	"cv hamfolah yarabi ",
	"cc hi slam nchalah rak cv ",
	" esq posible tfahmni info ",
	"saha ma3lich ",
	"cc habouk 9awanin ta3 elt ",
	"gir hadik ",
	"hada makan ",
	"ana kasni gir ndir conclusion ",
	"hhhhhhhhhh ",
	"esq 3andk ",
	"hambouk nsa9sik esq ndiro conclusiun tp 4 ",
	"cc ",
	"saha goli sit kisamouh ",
	"hhhhhh la eln ",
	"wah wlmath hya za3ma kolch bagya nimprimih ",
	"wzid chabginsa9sik kasni form pdf ta3 td elm bach nimprimihom ",
	"hambouk rsali sit ta3 labours ",
	"cc slam  ",
	"wah 3andi ",
	"haka ",
	"ntal3ah flpc ",
	"doka ana bach na9ra ",
	"pc tani mabgach yatla3li ",
	"mabgach yatla3li matlab ",
	"cv ",
	"ta3 labours ",
	"bhhhhhh ",
	"yadra ",
	"cc jabtlak lawra9i lyoma wnsit na3tihomlk ",
	"ana tani ba9ili tali ",
	"aaaaaa bgit nsa9sik esq rak hal tp elm tali ",
	"cc  gadwa jibli  ndir photocopi ",
	"aya saha ",
	" hambouk ta9dar dirli photocopi kalalsak gadwa ",
	"cc  yadra halit ex 3 ov ",
	"galoli rusume ",
	"elt ",
	" kasni tast ta3 l3am lifat ",
	"cc ",
	"merci  rabi yahafdak ",
	"tma 9balha yokraj aya say mala ",
	"saha tma cos m3a zawja ",
	"mochta9a ",
	"hadi rahi nichan ",
	"rabi yahafdak  sahit ",
	"aaaaa saha aya saya mala hkamtha ",
	"saha ",
	"mafhamthacg ",
	"hi kasni hadi ",
	"cc ",
	"kima hna ",
	"ykamlolkom m3a 14 haka ",
	"aaaaa saha ykmlolk bakri ",
	"aaaaaa haga nta 10 ",
	"drnah sinana lifatat ",
	"no gadwa makanch tp nkmlo 3la 13 ",
	"cc gadwa nroho maktba na9r ",
	"aya ok ",
	"wgbani ",
	"wah ni dayra bih ",
	"ya9ra wifi ta3linpartagih mn3and mama bsah ta3dar mayabgich ",
	"saytha ",
	" pc ta3i mabgach ya9rali lwifi ta3 dar ",
	"cc ",
	"jma3a galak gadwa hadak azous rwaho n9arikom 3la 8 wgalkom ta3 logic rwaho ndirlkom tashih ta3 tast ",
	"eaq kayan cour hchya? ",
	"🗿 ",
	"mazalha tamak ",
	"mlfich 1 ",
	"svp  ps chagalna na9ro ",
	"gatana machi daklin ta3 lcour ",
	"sala jma3a svp kasni solution ta3 math fich 3 ",
	"sbp kasni vd fl youtoub yfaham la diode ",
	"esq  3andkom tast ta3 l3am lifat ta3 math ",
	"🦾 ",
	"nta outo ",
	"nzido tik tok ",
	"tlgram mir ",
	"hadi ostori twaswastlha ",
	"hhhhhhh snap ",
	"malki koti hambouk ",
	"li bagi  ydkol ",
	"aya rani hala grop fl insta ",
	"wah mardi ",
	"wahdafihom  normal mohim flclasa 5103 ",
	"tma jma3a gadwa na9ro sbah ",
	"ma3lich rwah 9ra m3ana ",
	"hhhhhhhh bdlok ",
	"wlit aouto ",
	"chachjabk nta hhhhhhhh ",
	"9isach  wwin ",
	"konto gotoli na9ro gadwa ",
	"slam ",
	"nchah hambouk ta9adri gadwa tgolili lasal wga3 ",
	"maktbatch  sn sahiti koti ",
	"wnji ",
	"golt nn3al chitan ",
	"hhhhhhhhlt njihh ki 3w ",
	"makanch ",
	"bgit nji nchof kidayra ",
	"ana mazal ga3 mahit ",
	"cour ",
	"li yroh ya9ra ",
	"esq gdwa sbah kayn fikom ",
	"bgit nsa9sikom ",
	"SLM JMA3A Nchalh tkono cv ",
	"Hada fl bf",
	"@Hanane🙂  madasrinich yaaaaa saha",
	"3andak sah",
	"Wmatzidouch tagoni",
	"Aya golilhom",
	"Samono straig wbroyd wli darnah ga3  bo",
	"Koti ch3al rahi sa3a doka",
	"Li kan yhawas yafham chadakal",
	"@tous",
	"@tous    Mis:     Tout est inclus  dans l'examen  sauf lindentification en BF",
	"Haka sma3t ana galo aya ni nkama lagadi ydit kolach fiha",
	"Esq hadik iso 9001 hya li dar 3liha formation",
	"Merci",
	"Li3andah",
	"Kasni hadak  ta3  élevé  moy  faible",
	"Chkon 3andah exm ta3 l3am lifat uc  svp",
	"Hada fih charaki thawsi",
	"Chkon 3andah exm ta3 l3am lifat csl",
	"Conx",
	"@tous",
	"Bonjour.  Mis a 12h 30 a l'amphie A 7",
	"Wah normalmont",
	"aaa haga c++",
	"Aaa wtani li ya9to tnin",
	"@tous",
	"Gatalkom ta3 ep tp li 3andah tp ta3 jeudi simana jaya  yjiha hadi simana b jeudi  tma les 2 grop",
	"No, I even made renovations to improve",
	"Rakom magmomin ldarajat soual dahakom",
	"Jma3a rako tbano 3andkom ch3al madhaktouch",
	"Gadwa jma3at ep 3la 8 ta9ro?",
	"@tous",
	"Gadwa nchalahmakanch mis",
	"@tous  gadwa na9ro uc sbah?",
	"?",
	"Ana ni ngol cha galoli goli",
	"Ana chadaklni",
	"@tous",
	"Wboumadyan gal tank ydi sa3at lep li rah bagi yrohlah sbah",
	"Tma rah na9ro 2h30",
	"Gadwa nchalah mis t9arina sa3atha wtzidna sa3a wahda zyada",
	"Chkon ya3raf kach wahad fl youtube yfaham csl",
	"@tou",
	"Hatab rsalalkom solution",
	"La matkafich uc mamaditlahch limail ta3i",
	"Li ya9dar yhothom fl draiv yhothom",
	"@tous",
	"Esq galalkom ntoma fl tp nn gal ll3adil wahdah",
	"Tlata nchalah",
	"Machi lyoma",
	"@tous",
	"Rwaho",
	"Rana 5103",
	"Wah gla3tli staras",
	"Sa3a rak dirana fl fokaha",
	"Ana hsabtak rsalt kacb ex wla",
	"Salam chkon le grop ldaro tp mis hadi simana   @tous",
	"@tous",
	"No makanch",
	"Wah 9balh",
	"@tous",
	"Hadi mis",
	"Chkon 3andah les 2cour lwala ta3 eq yarsali  svp",
	"Bgit gir ngolkom ljma3a li tabgi tahdar 3and hatab rah ydir lcour 3la 12:30 nchalah",
	"Tma ntoma kasrin",
	"Aaaa ana tilifouni fih lfadaih tawa3kom",
	"Aha jma3a hada gor amin dawlah tilifoun",
	"Ana ni n9ara3 gir kach fadiha 3liha ni mkalyathom",
	"Chadaratlak chahinaz",
	"🤣🤣🤣",
	"Dawlak tilfoun",
	"@admin",
	"Lig mol le grop hwa ydirah",
	"Diro sondag li nchofah bzaf ngolah dak hwa",
	"@tous",
	"Ok saha",
	"Galkom htab 13:00",
	"Ana li golt lprof",
	"Adi hna tani ma3adnach sa3a kawya na9ro manahbsoch",
	"Hhhhhhhh hna tani td 6 ml makanch wa9t nrayho fih",
	"Hhhhhhhhh 😅😅 say batalt",
	"@tous",
	"Say ni rsaltlah yrpondi ngolkom",
	"Rah narsalah imail wnconfirmilcom",
	"Normalmont galana, 3la 12:30",
	"@tous",
	"Li td 6 ygoli najotih",
	"Ok",
	"Ni halit grop",
	"Chkon grop td 6",
	"Daw ga3 zhar",
	"Li taho fi grop 4 moh da3t lih wnas d3awlah wga3 lomahat t3awlah blkir",
	"Ana",
	"@Smd Bene",
	"Chkon td 4 bagi td ybadal td 6",
	"Ana td 6 bagya td 4 chkon td 4",
	"Dir nta",
	"Nasiha nsahom kima yansawna ki yatfakro njo wsay",
	"Matahsihomch hadok tbalhom 3la 12 yaraslo",
	"Adi tawa3na hata flil ytfakro bli magalonach na9ro aya yraslo",
	"Chkon aslan délégué",
	"Yakadmo sbah",
	"Sbah yhalo m3a 10 haka",
	"Rahom ymado fiha",
	"Winta  Entrée à l'université",
	"Prof joup",
	"Chkon 3andah lhal ta3 fich td 2",
	"Chkon ya3raf fb ta3 hadak mager de promontoire",
	"Ki ya3tona cos(£) kich nrodoha ton(£)",
	"Chknon 3andah 9awanin fich 5",
	"svp kasni ex 4 fich 1",
	"Normalmon haka gali",
	"Jma3a mna lnhar lhad kolch ykon mahtot wyabdaw les rèclamation mnhar lhad 3and lbiro ta3 9ada  @tout",
	"Glk 9:50",
	"Prof mazalah dayar consultasion",
	"Sa9sih 9isach ykamal",
	"Gadwa nfawat ratrapag ygibhali wahd fikom",
	"Sbah 3tohni ndihlhom",
	"Yak rahom mafichynlkom tp mn",
	"Brahim ktab lwar9a nta ana mana3rafch changol fiha wla chaba Kyan",
	"Ma3labalich charakom bagyn tahadro fiha",
	"Mohim @tout ana sbah 3toni lwar9a msnyn fiha na3tihalahom",
	"Ni msa9sythom 3liha",
	"Ana ndilah",
	"L3am lifat 9:80",
	"Merci",
	"Wah 9:50",
	"6 min jabouha",
	"Saha dir lkir wjawabni",
	"Mabgach yan3al chtan wyatsagad rah kachafni hda l3adyan",
	"Tp wla td",
	"Td",
	"Tako 3la tp wla tu",
	"Kayan bzaf madalhom 3ad ktar mni sa9so tayab",
	"13,75",
	"Kayan ana w wahdin ya9ro m3a y’a",
	"Tma n9ati 3la 20",
	"Jma3 rah kayan li madalhom fog 10",
	"Jma3 n9ati 3la 20",
	"Hada chaf rohah b3id man9adoch nl9oh aya zakar",
	"Nzidkom haja kon tahadro m3a tmimi tani mliha",
	"Mohim goltalkom chadiro psq marahch yji hadak wla yasma3 bikom",
	"Ana kan 3labali haka wgotlkom bli kalo tamimi ydirana",
	"Tma la rakom bagyn tahadro roho llbiro ta3 daou",
	"Homa li y3aytolah",
	"Mohim lhal doka rah 3and daou wla zonâtes",
	"Prof hadak ma3andahch biro",
	"Svp",
	"Kasni ratrapag ta3 mee l3am li fat",
	"Kayan li jaw 3andi prv galoli raslina rsalt li 3andah chihadra ykaliha 3andah",
	"Lcs",
	"Majitch chaft",
	"Ddp",
	"Chawala dép",
	"Bsah hna kayan les 2",
	"Whna kayan les 2",
	"Galana horésontal",
	"Mchachi prof fl exm",
	"Bagya nsa9sik OM",
	"Aya wahad 3andah yarsal ida 9ad",
	"Raslili",
	"3andk",
	"Sécurité",
	"Chkon 3andah résumé se",
	"Gadwa chakayan ratrapag",
	"Bach yconfirmili",
	"Ana gali sapt bsaha gali hta n3awad nesalak",
	"Jma3a chkon gadi ymad lprof ta3 tp salc  tp",
	"Jma3a  esq kayan li mahatolahom walo fi progras ta3 s4 mkalnlhom kolchi Kaci",
	"Wga3 na3arfo nrabho l3ayb gir manabgoch",
	"Prof rahi t9ara3 fikom",
	"Jma3a li mafawtouch tas ta3 ts lawal",
	"Win sall nfawto fiha ts",
	"Chkon madarch tast ta3 ts lawal",
	"Machi haka",
	"Raki galta fi katbatah",
	"Hala li rak fiha hya li tchaf",
	"Nn machi hado li yza3fo wla y9al9o",
	"Rak kala3ni wlah lahili ldaraja ana wmalahyach rohi haka",
	"Ma3lich nt3alam bchwya psq machi mwalfa naktab",
	"Nta chah grop",
	"Sagalito mabgach ysta3raf rah yba3ad chobohat",
	"Harzo fb taw3kom",
	"Za39at 3lih dahlha",
	"Wah naman srat hdaya hwa dalha",
	"Dalha fb ta3ha",
	"Adi mskina chira l3am lifat 9anatha hram 3lik",
	"Chaft  bli mana3rafch nta ta3raf",
	"Ha li yafhmni",
	"Saya gadi doka nsagad katba",
	"Bchwya",
	"Ni nt3alam",
	"Sahit",
	"Wah",
	"🤣🤣🤣🤣. Dawah",
	"Wga3",
	"Rak mvid t9ara3li naktab",
	"Harzo *",
	"Wah hardi",
	"Dirakt",
	"Ya3tona x wl. Y",
	"Wah",
	"Bsah katrat maymadonach",
	"Tayab chawala Fnc",
	"Bsah kayan.  A. T.  N. Fnc",
	"Ysalmak Kori",
	"*",
	"Fnc",
	"Fi la méthode ta3 lagrange chawalah hadak.  Donc",
	"Mohim salc galkom gadwa jibo tp wzid exm",
	"Goltlkom mayhamah ni 3id talaba wla listi9lal y sir",
	"Hadak gadi yji mn bl3abas marahch yhawas yafham ida 3id talab wla ga3 list9lal ydir ydir",
	"Wsalc magalich wma3ayatch tma makanch .",
	"Jma3a madam hta prof ma3ayatli wla rsali tma kyn exm tp mn",
	"Wraki tfakri fya",
	"3ajbatni ki tagitini hna hasit bli Ana zalmat wla da3o hhhhhhhhh",
	"Rsali la part li fiha systam automatiq",
	"Ida tala3tah fl pc",
	"9Rah tani",
	"Systam automatiq",
	"Nn",
	"Synchrone, asynchrone  AC, DC, pas à pas",
	"Hado zido 3lihom gir les motors lilting",
	"Hada tani",
	"Madarnahch",
	"No",
	"@Leila Ch",
	"@Farouk Farouk",
	"3Adna 5moteur kolch",
	"Jma3a  chapirt 1ma9rinach fih kolch wl 2 kmlnah",
	"Mafhamtch",
	"Oui",
	"Hada makan",
	"Fich 2 et 3",
	"Li Malachi",
	"Hado li darthomna sapt",
	"🙏",
	"Svp kasni chadarto fl cour tali 3andah esq des exs",
	"Mazal mabdat",
	"Jma3a rana fl A1",
	"Classe de cour",
	"Psq nta mlbarah tfatach 3la sall na9ro fiha wt9ara3 fi daou 3liha rak jay dir moharij jna dir haja taslah wrwah hdar aaaa li 3andah 3kal   Mdasra .",
	"Prof ta3 lcour",
	"Sapt nchalah ts 3la 9:30",
	"transractreur  hada",
	"Tma zawaj ma9rinahch",
	"additionner we transractreur  hado 9rinahom ?",
	"Galatlkom prof ts  lkmis mor exm ta9ro 3andha   Win mazal ma gatli",
	"Dach rah mhabas musur fl chapitr",
	"wmarahch msa9siha hwa tma li ya9ro 3andha 3la 11 mayjouch sbah 3la 8:00",
	"galkom prof salc tp machi ana n9arokom prof ta3kom 3la 11",
	"chakom bagyb tani",
	"say hada mansa9sih",
	"koti nsa9silak wah   bsah katra jaya hadri m3aya avec respect ok",
	"wla tfahmo",
	"l prof",
	"les grop li ma9rawch lhad li fat ya9ro hada lha  li 3andah problam ygolah",
	"gotlkom kima gali",
	"hada win 3ayatli wgali",
	"tp  salc grop 1 et 3 a 8:00 nchalah",
	"les 2 firahba",
	"grop 1 w 3  a 8:00",
	"katik marwan hada wahad glat",
	"rah ykalatkom",
	"dar parie2 wgal ni galat",
	"rah galat",
	"fl majal li li yadih fl intgral",
	"hada rah galat fih hada mograbi wrah galat fl ex nata9roch 3lih",
	"lcs",
	"marakch dahak 3labalk rak dir ki bzoz",
	"tcs",
	"galkom 3la 13 gadwa nchala",
	"gotlah kayan td",
	"lcs rsali gali ,lhad 3la 12:30",
	"ts rahi rayha simana jaya",
	"na9adro ndiroha moraha",
	"wah 9gotlah",
	"jma3a 9isach tsa3adkom nhar lhad y9arikom ta3 lcs joup",
	"👌👌",
	"mohim ana rah narsl lprof ts imail ngolha sapt",
	"ni m3a les prof ni dpartemon",
	"apar tamimi hadak wahdah",
	"les prof maka madakalhom rahom kofna problam fl dpartemen",
	"lafich talya",
	"ana oma ni nsay li bagi yafham uafham kima tabgi hbiba tbgi tji tabgi la",
	"wah",
	"firahba",
	"dik hya na9rohom les 2",
	"tani t9arina sapr",
	"aya ngolo l ts",
	"saha lcs l9itah gbila hada sapt galkom njibkom ndirlkom ex 4",
	"hhhhhhhhh  mliha hadi 😂😂😂😂",
	"hhhhhhhhhhhh 😂😂😂😂😂😂😂😂😂😂",
	"normal",
	"3ajbatni hadi hhhhhhh",
	"homa 2 gos w gos jordn",
	"cour ta3ah",
	"habsna fgos gordan",
	"lmhom lhada l3am",
	"galak l3am lifat madar wala tast",
	"wah hwa gali hada lhad bli mor lexm",
	"salc gali narsalk mazal ni n9ara3lah",
	"aya say rana flintidar tma 9ra lmail ta3i salamat",
	"prof gal kayan",
	"tp",
	"wkamli m3a ljami3a darba wahda",
	"jatni 9ro tani ts",
	"samdi kayan 3and lcs",
	"ma3lich kon ytal3ona mangoloch la ykalohom 3andhom n9ati",
	"hhhhhhh habsi  ymadona n9ati ta3na dal3am wmba3d hadri 3la 3am jay",
	"dof ida ntoma bgito tdoklo diro exm bl swalah ma9ritohomch fl td",
	"psq mazal ba9i ma9aratnach chi swalah fl td",
	"hadi gir le grop 4 w 1  li ma9rawch td lbarah",
	"chaft ana kasni charahi katba prof",
	"li katbatah prof",
	"ni masha9yatah",
	"saha li rah 3andah cour ta3 convolution ts sat9a 3la ealdih yrsali",
	"merci hasni rabi ywaf9ak nchalh ntatani",
	"golna",
	"da3wat lkir",
	"chkon rah 3andah cour ta3 la convolution ts",
	"kasnibta3 la convolution",
	"hya prof darath li maya9roch 3andha td gatlhom t3awad lafich talya dirhalhom lasal li mwalaf na9ro fiha cour 3la 9:30",
	"nrsaltlah imail fahamtah kolch chakayan bli lcour bga hwa ydir wgotlah ydirana mor lexm",
	"oui",
	"aya saha",
	"aya sah tast mor l exm wmaydirch tamimi ta3 tp",
	"hadahwa lproblam",
	"lhad lana mafhamtkomch changol l daou ndiro wla nn",
	"bahartohali cha ngolhom bagyn diro tast wla nn",
	"saha chakom bagyn bach nroh gadwa nahdar",
	"kon hdart lcour lbarah ta3raf bli ta3 lcour galan ana ndir tast",
	"troho tahadro gadwa ldpartemen",
	"aya chatfahamto",
	"kayan wah",
	"matfahmouch 3la haja wahda y9arouhana",
	"ta3 tp ygolk ni n3ayat ta3 lcour wlcour ygol tp ma3ayatlich",
	"nn hbiba fizoj galtin wahd fihom galat ktar mlakor nhar lawal ytfahmo 3la program",
	"tast ydiron  haja machafnahach ki",
	"ana li  rahi mdrongytni que kol wahd fihom bagi yafrd rohah tp ygolak ana wtmimi ygolak ana    whna tafrat fina",
	"matansawch gadwa ta9ro ts 3la 9:30",
	"mazal masahah hbiba",
	"wah hadi hya  li ni ngol fiha mongbil dabro risankom ana roht hdart m3a idara galak hna katina daou tma ya ttfahmo wtatal3o ya tsralkom kima s3",
	"tamimi",
	"ni goltalkom prof mayasta3rafch bya wahdi li9 oma ykono bzaf mli ya9ro m3ana lbarah na nahdar m3ah whwa ygoli li makich fahmatah nfahmahlk ana ma3andich problm kamamt fikom",
	"mohim ana dart li 3lya wgoltalkom chakaskom firo wcharah kayan tab9a 3andkom ntoma nhar lkmis  tmimi galak ndir ana cha9arit   wtp galak ana cha9arit",
	"hhhhh 0 yhotohlk tani sahla",
	"ana hadi lyamat wlit",
	"li9 ga3 tjo wda3o hwa li yafrihalkom",
	"psq gali hadak 9ada",
	"ntal3o ldpartemon nahadro m3ahom ga3 bsah",
	"tma li9 nhar lkmis ki njo na9ro 3and ts",
	"li fhamtah mnah hna les delegues rah hasab hna mabginach wntoma rakom bagyn",
	"ana hdart lbarah m3ah 9bal mangolkom",
	"ya les 2 prof yatfahmo ya maydironach",
	"ya fah nahadro l dpartemon 3la hada lproblam ya rah yasrana kima S3",
	"marahomch m9arina kifkif lmohim",
	"mochkila kol wahad fihom charah m9afi",
	"wta3 tp galak nn ndiro lhad",
	"slam jma3 ji tngolkom bli prof ta3 cour mn tamimi hwa li rzh ydir tast de tp wrah ydorah mor les exam haka gal lbarah",
	"🌤",
	"wah makanch",
	"galkom makanch gdwa ta3 lcs",
	"ygoli 9isach ngolkom",
	"demain normlmont",
	"aya ok rah bgolha lkmis",
	"nn ma3adnach",
	"yadra changolalha lhad wla lkmis",
	"nn hadi ta3 ts",
	"J'espère que mon message te trouve en forme.  Voilà donc après réflexion, je vous propose de faire la séance supplémentaire le dimanche 4 mai ou alors le jeudi 02 mai avant 11h vu que je serai prise à partir de 11h.",
	"salam gatalkom prof kayro nhar",
	"wah",
	"ta3 deigram de bord",
	"salm svp kasni le cour ta3 salc li rah katab",
	"jma3a li ma9rawch tp lyoma tal3o l dpartemen gololhom",
	"hado la solution ta3 fich 4 salc",
	"oui",
	"tal3oh fl pc yatla3lkom",
	"si kayan",
	"gatlkom prof hadik ta3 fronc gadwa n9arikom",
	"gatalkom ta3 mn gadi yzidona gir ex ta3 gos",
	"3tawahni idara",
	"wah doka",
	"galkom hada hwa final",
	"rani fl dpartemon",
	"nn badalnah doka",
	"doka",
	"rahom badlo",
	"salam",
	"tagoh bach ychof",
	"@Ghozali Sam  svp fahamna",
	"????",
	"s6",
	"chahada sondag",
	"jma3a mafhamtch hada ta3ach",
	"3and hadak",
	"esq na9ro cour",
	"kyn wa9ila jraj ln hada le grop",
	"ta3 hchya",
	"slam jma3a 9isach na9ro cour",
	"wsaha ftorkom",
	"jna3a salam galkom prof de architecture gololi gadwa 9isach tsa3dkon n9arikom",
	"amin",
	"nti tani hbiba tsomi bsaha nti wdarkom nchalah",
	"jdida tani manicha 3arfa chabadal prof",
	"prof gali rslthalah",
	"@Ghozali Sam  rsalna fich td ta3 salc",
	"makanch fikom sawro lalist wla",
	",",
	"chkon li 9taw td  salc",
	"bsah",
	"gir salc",
	"@Ghozali Sam  esq rsalolk les prof kach fich td wla",
	"sahit",
	"tma 9raw lyoma tp 2",
	"tp1",
	"lyoma chkon tp 2 wla tp 2",
	"ktabto ismawatkom li hdarto",
	".",
	"esq darokom binom",
	"makanch 5",
	"hhhhh",
	"nta td chah",
	"wah",
	"wah gadwa ybdaw",
	"fl lapag normalmo yaficho",
	"madam maafichawch",
	"bli",
	"ha chafto",
	"la ba9i s4 koti na fi bdyatah  s3 wmazal ma afichawah",
	"sahla  kayan bzaf bnyadam bagyn ydiro dlg wyastahlo  tfahmo wsay",
	"machi tani haAk sami",
	"ch3al kayan mn dlg hambouk",
	"li bagya ngolah  3adna ha9na hna tani machi kima ybgo",
	"tani msag fnos lili aya nroholhom sbah  kon ba3da afichaw",
	"daro exm ki kaml s3 golna ma3lich mazal maafichaw golna ma3lich  maymadonach les td ma3lich",
	"hadi ga3 makanch mnha  li yroh gadi ybayanlah bli hna les etudion machi bnyadam mat3ayach rohk ksar 3lina imaill fnos lil aya ngouk makanch mochkl",
	"doka ana galta dkalt grop nchof bli galkom gadwa rWaho",
	"makanch ga3 mnha yarsal imaill haka    normalmon yhot flapag wya3lm",
	"gir bgir na3raf la btablya wla nn",
	"la simana jaya",
	"esq tp btablya",
	"merci",
	"svp  program de  td1",
	"nn simana jaya",
	"merci",
	"wah",
	"chkon 3andah program",
	"winta ya9ro",
	"jma3a td 4",
	"nsit bli nta bdalt auto",
	"hadak prof ta3 mn mayjich lyoma ?",
	"ha li9",
	"nwarihlk",
	"rohilah koti",
	"wlah nas mlah ttsa9sih yjawbak",
	"mmmmmmmmm",
	"mala kich 3rafti bli machi mlah",
	"la hadi ta3na matatwaswasch",
	"hado jdod",
	"ana hadak hatab wta3  archi....  banoli mlah",
	"la",
	"hamdolah elt 3andah gir cour",
	"hawji  ana ni mtfaala",
	"kayan  holol lard",
	"koti 3andak normal kayan racha",
	"3lah raki tgolilha haka",
	"nchalah yarabi",
	"wah ana tani haka l3am lofat",
	"aaaaaaa st konti",
	"ni ntala3 rohi m3ak",
	"kifach nti bgiti y3awdi tama koti",
	"3adi kili da  1  2 3 4 5 6 0 kifkif",
	"wah  9adar tbal3i s4 wmatbal3ich s3",
	"normal",
	"rana ga3 firahba matkafich makich wahdak",
	"hya nafsya mayatarch bsah mo3adlyan yatar",
	"3awdlhom",
	"simana jaya",
	"exm",
	"rahom chafini li rah ydirlhom",
	"kon tbal3o ratrapag",
	"td",
	"eln haka wgatana nbadlhalkom",
	"oooooo bsaha",
	"mata9adich ta9ri fl s4",
	"ha li9 tat3amli boroda tmardi rohak",
	"normal matnarvich rohk",
	"aslan ta9ro ntoma 3la 8",
	"walo",
	"nn machi da",
	"matn3alch chitan wtarsali",
	"nn hadi simana",
	"aya wrak li kont taktab wgotlak mba3da swarli wrsali",
	"slam",
	"hado ana jbthom mna",
	"merci",
	"tma (7 4 2           1 1  1            26 5 1)",
	"ones (1,3)",
	"hadi chama3naha",
	"wkayan matrs",
	"hado li darnahom",
	"tayab kayan gir   if  for",
	"gadwa sbah 9isach ov",
	"say fhamt",
	"aaaaaaa saha",
	"kifach to elm ndiro tast ?",
	"winta nabda bsqh",
	"diro consultasion",
	"wrakom",
	"wah",
	"mazal wahd simana haka wla",
	"kolwahd ya3rf ro7ah capabl 3liha ygolna whna ndiro vot hnaia sondag",
	"mazal  normal sa9sithom",
	"bach ywali yhot s4",
	"li9 nkyro wahd",
	"nn L2 maknch",
	"win bsah",
	"sall?",
	"wla win",
	"4etag",
	"gadwa hadak eta dlar win",
	"hadok st",
	"chkon yalha yafichi doka",
	"afichag 3la 12",
	"ntoma morda",
	"marahch yzido yaficho",
	"doklo chofo",
	"nn raslatah lina",
	"machakitch",
	"mlih paga haka",
	"mskina",
	"amirat doklo m3aha",
	"3lah rakom m9al9in fi gardhom normal",
	"ya win jay ?",
	"wah",
	"birouh win jay",
	"mazalha tmak",
	"gadwa",
	"kidayra sall eln",
	"mor les vaconce ndiro les exm",
	"m",
	"ni nsa9si fikom ida hadi eln",
	"hadi eln",
	"ch3al dit nta rayan",
	"salamat",
	"wah ana hsabt 0",
	"la wlah hamdolah ana dkalt g3at nsf lmoda hadik ktbt ismi la9bi wkrajt",
	"aaaaa ma9ritch mohim",
	"prof ismi wla9bi 3tatni 3lih 1,50",
	"kla3toni 😭😭😭",
	"3lah goltoli elt",
	"aaaaa eln mach elt",
	"min jabtdo lwra9i",
	"ntoma rohto ljami3a wla kofah",
	"😕😕 makanch consultasion",
	"tah exm wla chah",
	"hado ta3ach",
	"wah ma3lich nti makasra walo tdokli  wida bla3ti bl s4 y3adohlk",
	"la  machi gaya tbali ana nkono nsina kolch fl s3",
	"ana wlah mafhamt  walo  normalmon kima l3am lifat wsay chawala ratrapag ta3 s3 ysirohna 9bal 34 wsay",
	"ma afichawch bsah",
	"w  s4  winta",
	"winta ramdan asln",
	"la ta3 blgayad firamdan tani",
	"chkon gal rak mnytak tma machi fi sayf mliha lahak",
	"rak m9ala9 larwan",
	"wah esq hadi simana wla simana jaya",
	"chagalona info na9ro",
	"wla engl wahdha",
	"svp tq9ado tarasloli draiv lifih kolch",
	"fich 5",
	"3andk lhal ta3 ex 3",
	"merci",
	"winta ndiro  I2cc=I2n",
	"merci",
	"aaaaaa saya wah",
	"lawla ga3 ftamrn",
	"mamadouhach",
	"ex 1 fich 5",
	"kich njabdoha",
	"ra3ch",
	"P?",
	"Pjoul = P?_Pfer",
	"kasni  draiv ta3 eng",
	"svp rasloli lhal ta3 ex 4 fich 2",
	"tashih",
	"adi ana tast 1 wmadartahch",
	"waha say  fhamt",
	"chakla hata ratrapag aya li kon mrid  ymout",
	"esq ratrapag wla 9bal",
	"aya winta y3awdoli",
	"salam jma3a bgit nsa9sikom  kon wahd y apsont  fl exm  esq y3awdohlah wla nn",
	"sahir",
	"ps",
	"kasi suj  ta3.l3am  lifat.pc",
	"merci",
	"svp ps chana9ro",
	"normalmo ykalona",
	"ana twalft na9ra biha fdar",
	"marvisinach 3lih ma hwa sahl",
	"wenerg esq ga3 draiv wla gir  wahdin",
	"eln chagtna dakal ga3",
	"wah ga3 na nkamo haka",
	"kifkif tahsab la somme bach tjba id  cv  wla dv",
	"mafihch lhal ta3 fich 3 hada",
	"hafa fich 4",
	"hada kon nhalouh firahba wmanfahmouch chanktbo",
	"chkon rah faham hada",
	"mayfirch haka  gadi ydir qcm",
	"kach mab9a hado lasila",
	"hhhhh hada 2016 kont nfawt fl 1ans sem",
	"raslih bla matgoli",
	"hhhhhhh lcour fih 35",
	"eta de lare ?",
	"rpondi prv",
	"da li ktabt ana",
	"chwya",
	"ana mdit lhadak li galna 3toni",
	"hhhhhh 3lah",
	"_hak hada",
	"kol wahad win fawat tast y3awd yfawt exm",
	"jla3a nfawto fles sall ta3li darna fihom les tast yak",
	"merci",
	"slam chkon 3andah exm ta3 l3am lifat ov",
	"merci",
	"sala jma3a svp kasni solution ta3 math fich 3",
	"hhhhhhhhh",
	"@Ghozali Sam rahom ycharo 3lik",
	"hadi l3am lifat machi dal3am",
	"matlab  hhhhhhh",
	"sah fl info hada makan",
	"rahi gaydtni gotlah ijaba nichan wmagalich nzidak",
	"ha chofi ana tani ni m3ak",
	"wah koti hhhhhhhhh",
	"wah 3andah sah ta9fo chwya",
	"chanahsbo ma3raftch",
	"ma3labalich galak fiha hsab",
	"hada wla 2",
	"fach habas",
	"wla nn",
	"hadak prof ta3 energ kamallkom program",
	"nsy mohawala",
	"svp kasni ismawat ta3 les cour ta3 mah lafich 3et 4",
	"chkon 3andah imail ta3 priph ps",
	"KASNI PS PROF  EMAIL TA3AH WLA",
	"slm chkon y9arihom proph ta3 PS TD  HADAK TA3 COURE",
	"kasni sit ta3 labourse wkifach nsagal fih",
	"merci",
	"svp",
	"sbp kasni vd fl youtoub yfaham la diode",
	"tma machi kima hada l3am",
	"9rinahom fl cour",
	"esq  3andkom tast ta3 l3am lifat ta3 math",
	"chkon 3andah program ta3 les tast",
	"wah galolkom chofi les liste flapag li mal9ach ismah yji ygoli lyom wla gadwa",
	"merci amin",
	"syaha ntiya  ana hsbt biha",
	"aya saha",
	"hata wtdorbi rah yroho bliktizal",
	"dja rah taktazli koti",
	"no drabt ana",
	"ana 0.04",
	"wah",
	"hak toul ta3hom",
	"ana tani wfahmni",
	"kima ana l9it kich rsamti rasm",
	"wah na9ro",
	"nn  omga 0",
	"moyennes",
	"0.7     w 1.5",
	"kifach",
	"ana say halit kasni rasm nxhofah bach nchof ida ni galta wla no",
	"slm jma3a chkon hal tp ta3 ov",
	"ana bakart wjama3t lawla w kaltni",
	"ja ya3rag rah ya9ra lha talfatlah",
	"ta3 lmath mskin  x 9raha y",
	"yahsan l3awn",
	"bsah nas mlah",
	"prof hadak tali darna chapitr kima darat",
	"jma3a ki ma9ritohch chapitr kima dar ga3 fi   45 min  madarto walo",
	"hnouda hada yahslha",
	"tayab golha",
	"raki dalmathom sa9sini ana ztayab",
	"hhhhhh  hadouk wahadhom",
	"yahsolha",
	"hnouda mlah  ana ngolk",
	"ana ml bac na9ra 3andah",
	"bac",
	"ni na9ra 3andah mlbav",
	"aya nwalo bras wsay",
	"ana youyoub krjoli lhnouda",
	"saha jma3a makanch ga3 proph ta3 math nroho na9ro 3andah",
	"wah",
	"makanch proph wakdakor",
	"yfaham tani",
	"ana 9arani houhou",
	"ma lmath normal",
	"haka",
	"la hwa li dayar hama",
	"hhhhhhh adi hya hsabtha ntya @Leï La",
	"lmath hadak wahdah",
	"@Soheib Djm  wlah hsabtha  hya whdart m3ak dak nhar wana hasbatk hya",
	"mala hsabtak hya",
	"aaaaa no lkmis glt",
	"lhad nmadahlwnti sapt 3tijlah",
	"rah 3andi",
	"aaa nti li maditili expo ta3k",
	"ni 3la li bagi ymadlah",
	"mohim lkmis jay jibahlah",
	"hhhhhhhhhh  nsit",
	"wah ni gir nza39",
	"@Rayan Øfïsÿāl  glna ndiro expos",
	"auto s3iba",
	"jatno elm",
	"hhhhhh",
	"wla auto",
	"elm",
	"nta chata9ra  rayan",
	"hhhhh",
	"wah kamlha 9wta9i",
	"rakom raslonha",
	"rahi kaynapdf",
	"hhhh wnzofkom kmlna chapitr ga3 kimadar",
	"no gallom simana jaya jibouhli",
	"salm  aaa  li mafalo expo ta3hom bach nmadah lproph  madahch 3lya galkom simana jaya jibouhli",
	"hhhhhh kahlo kahlo",
	"merci",
	"svp  kasni l omploi du tomp",
	"salam jma3a chkon ikom td 5",
	"ana tani",
	"tbali rahom bzaf fi grop wahad",
	"kich 3raft nta",
	"sahiti",
	"tawal",
	"esq kima lawal",
	"wah bsah les sall wwinta",
	"ma 3raftch",
	"bsah winta na9ro",
	"aaaaaa wah  hhhhhh say fhamtak",
	"3lah",
	"wah",
	"aya  wkifach na3rfo wint na9ro",
	"hatona les grp",
	"gadwa kidayr sall na9ro fiha",
	"."];
